version: '3.7'

services:
  mysqldb:
    image: mysql:8.0
    container_name: database-mysql
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      TZ: Asia/Ho_Chi_Minh
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - $DB_PORT
    networks:
      - nw_template
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - nw_template
  app:
    image: app:latest
    build:
      context: .
      target: local
    container_name: app
    platform: linux/amd64
    env_file: .env
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - .:/backend-manage
      - '/backend-manage/node_modules'
    command: npm run start:dev
    networks:
      - nw_template
    depends_on:
      - mysqldb
      - redis    
networks:
  nw_template:
    driver: bridge

