version: '3.7'

services:
  mysqldb:
    image: mysql:8.0
    container_name: database_mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: $TIMEZONE_TEXT
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./docker/mysql:/var/lib/mysql  
    expose:
      - $DB_PORT   
    networks:
      - nw_template
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - nw_template    
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: app
    platform: linux/amd64
    env_file: .env
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ./src:/builder/backend-manage/src/
      - dev_dep:/builder/backend-manage/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn
      - prod_dep:/prod_dep/node_modules
    command: npm run start:dev
    networks:
      - nw_template
    depends_on:
      - mysqldb
      - redis
networks:
  nw_template:
    driver: bridge

volumes:
  yarn_cache:
  dev_dep:
  prod_dep:
