version: 2.1
orbs:
  node: circleci/node@5.1.1
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build_project:
    working_directory: ~/backend-manage
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Installing yarn
          command: yarn
      - run:
          name: Build source
          command: yarn build
      - run:
          name: Test source
          command: yarn test    
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_ecr:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile_name: default
      - run:
          name: Set up aws cli
          command : aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 556267189010.dkr.ecr.ap-southeast-1.amazonaws.com
      - run: 
          name: Build docker 
          command : docker build -t backend-manage .  
workflows:
  backend-manage-pipeline:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - deployment-circleci
      - deploy_ecr:
          context: ecr-context
          requires:
            - build_project
          filters:
            branches:
              only:
                - deployment-circleci