version: 2.1
orbs:
  node: circleci/node@5.1.1
  docker: circleci/docker@2.4.0
jobs:
  build_project:
    working_directory: ~/backend-manage
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Installing yarn
          command: yarn
      - run:
          name: Config environment variable
          command: |
             echo "NODE_ENV=$NODE_ENV" >>.env
             echo "APP_PORT=$APP_PORT" >>.env  
             echo "DB_PORT=$DB_PORT" >>.env
             echo "DB_USER=$DB_USER" >>.env
             echo "DB_PASSWORD=$DB_PASSWORD" >>.env
             echo "DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD" >>.env
             echo "DB_DATABASE=$DB_DATABASE" >>.env
             echo "DB_HOST=$DB_HOST" >>.env
             echo "TIMEZONE_TEXT=$TIMEZONE_TEXT" >>.env
             echo "TIMEZONE_NUM=$TIMEZONE_NUM" >>.env
             echo "CLOUD_NAME=$CLOUD_NAME" >>.env
             echo "API_KEY=$API_KEY" >>.env
             echo "API_SECRET=$API_SECRET" >>.env     
      - run:
          name: Build source
          command: yarn build  
      - run:
          name: Test source
          command: yarn test      
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_docker_hub:
    working_directory: ~/backend-manage
    environment:
      DOCKER_IMAGE: leduytien0801/backend-manage
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: echo "Deploy ecr successfully" 
workflows:
  backend-manage-pipeline:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - deployment-circleci
      - deploy_docker_hub:
          context: backend-env
          requires:
            - build_project
          filters:
            branches:
              only:
                - deployment-circleci