# circleci config
# version
version: 2.1
# orbs
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
jobs:   
  build-and-push:
    environment:
      DOCKER_IMAGE: leduytien0801/backend-manage
      DOCKER_TAG_APP: app
      DOCKER_TAG_MYSQL: mysql
      DOCKER_TAG_REDIS: redis
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: 
          name: Build docker compose
          command: | 
            cp env/.env.example .env
            yarn run docker-up
      docker:
        - image: demo:latest # primary container
          auth:
            username: $DOCKER_USER
            password: $DOCKER_PASSWORD  # context / project UI env-var reference
      # - run: |
      #     echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      #     docker run -d --name app leduytien0801/app:latest
      #     docker run -d --name redis leduytien0801/redis:latest
      #     docker run -d --name mysql leduytien0801/mysql:latest

      # - run: |
      #     docker build -t leduytien0801/app:latest .
      #     docker build -t  leduytien0801/redis:latest . 
      #     docker build -t leduytien0801/mysql:latest .

     # deploy the image
    #  - run: docker push company/app:$CIRCLE_BRANCH
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'
# test node pending
workflows:
  backend-manage-pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - deployment-circleci