# circleci config
# version
version: 2.1
# orbs
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: leduytien0801/backend-manage
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          name: setting environment variables
          command: |
            export MYIP=`ifconfig eth0 | awk '/inet / {print $2}' | awk -F: '{print $2}'`
            echo "export MYIP=$MYIP" >> $BASH_ENV
            echo "export NODE_ENV=$NODE_ENV" >> $BASH_ENV
            echo "export DB_HOST=$MYIP" >> $BASH_ENV
            echo "export DB_DATABASE=$DB_DATABASE" >> $BASH_ENV
            echo "export DB_USERNAME=$DB_USER" >> $BASH_ENV
            echo "export DB_PASSWORD=$DB_PASSWORD" >> $BASH_ENV
            echo "export DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD" >> $BASH_ENV
            source $BASH_ENV    
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'
# test node pending
workflows:
  backend-manage-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - deployment-circleci