version: 2.1
orbs:
  node: circleci/node@5.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
jobs:
  test:
    executor:
      name: node/default
      tag: "18"
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Run test source
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
workflows:
  build_and_deploy:
    jobs:
       - test
      # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
       - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::556267189010
          repo: backend-manage
          tag: latest
          dockerfile: Dockerfile
          path: .
          requires:
            - test