# version circleci
version: 2.1
# Define the jobs we want to run for this project
jobs:
  building:
    docker:
      - image: .circleci/node:18
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: | 
            npm install --save
  build_docker_image:
    docker:
      - image: .circleci/node:18 
    steps: 
      - checkout 
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 
          name: Build Docker image
          command : |
            docker build -t backend-manage - t leduytien0801/backend-manage:latest .
            echo $DOCKER_PASSWORD | docker login -u leduytien0801 --password-stdin
            docker push leduytien0801/backend-manage:latest 

# Orchestrate our job run sequence
workflows:
  build_and_deployment:
    jobs:
      - building
      - build_docker_image