# circleci config
# version
version: 2.1
# orbs
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
jobs:   
  build-and-push:
    environment:
      DOCKER_IMAGE_NEST: app
      DOCKER_IMAGE_MYSQL: mysql
      DOCKER_IMAGE_REDIS: redis
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: 
          name: Build docker compose
          command: | 
            cp env/.env.example .env.dev 
            yarn run docker-up
      - run: 
          name : Build APP 
          command: docker-compose build    
      - run: 
          name : Watch docker compose
          command: docker-compose images  
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'
# test node pending
workflows:
  backend-manage-pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - deployment-circleci