version: 2.1
orbs:
  node: circleci/node@5.1.1
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build_project:
    working_directory: ~/backend-manage
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Installing yarn
          command: yarn
      - run:
          name: Build source
          command: yarn build
      - run:
          name: Test source
          command: yarn test    
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_ecr:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile_name: default
      # - run:
      #     name: Upload file to S3
      #     command: |
      #       aws s3 rm s3://frontend-manage --recursive
      #       aws s3 rm s3://frontend-manage/assets --recursive
      #       aws s3 sync ./dist/ s3://frontend-manage
workflows:
  backend-manage-pipeline:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - deployment-circleci
      - deploy_ecr:
          context: ecr-context
          requires:
            - build_project
          filters:
            branches:
              only:
                - deployment-circleci